//<![CDATA[
var homepageurl = "http://phim850.blogspot.com";
function rutgon(e,g){if(-1!=e.indexOf("<")){for(var f=e.split("<"),k=0;k<f.length;k++)-1!=f[k].indexOf(">")&&(f[k]=f[k].substring(f[k].indexOf(">")+1,f[k].length));e=f.join("")}for(g=g<e.length-1?g:e.length-2;" "!=e.charAt(g-1)&&-1!=e.indexOf(" ",g);)g++;e=e.substring(0,g-1);return e+"..."}function altit(e){return-1!=e.indexOf("[")?(e=e.split("[")[1].split("|")[0],"HD"==e.replace(/\]/gi,"")&&(e="Full"),e.replace(/\]/gi,"")):"Ch\u1ecdn b\u1ed9"}
function titvn(e){return-1!=e.indexOf(e)?e.split("-")[0].replace(/(\[.*?\])/gi,""):e}function titen(e){return-1!=e.indexOf("-")?e.split("-")[1].replace(/(\[.*?\])/gi,""):e}numposts=36;
function thumbsd(e,g,f,k,l,h){2E3<Number(g)&&(g=2E3);e=e.replace(/s72-c/gi,"s"+g+"");data=""!=l||""!=h?'<li class="list-top-movie-item"><a class="list-top-movie-link" title="'+h+'" href="'+l+'"><div class="list-top-movie-item-thumb" style="background-image: url('+e+')"></div><div class="list-top-movie-item-info"><span class="list-top-movie-item-vn">'+titvn(h)+'</span><span class="list-top-movie-item-en">'+titen(h)+'</span><span class="list-top-movie-item-view">'+altit(h)+"</span></div></a></li>":
"";document.write(data)}
function htop3(e){img=[];maxpost=numposts<=e.feed.entry.length?numposts:e.feed.entry.length;for(var g=0;g<maxpost;g++){var f=e.feed.entry[g],k=f.title.$t,l;if(g==e.feed.entry.length)break;for(var h=0;h<f.link.length;h++)if("alternate"==f.link[h].rel){l=f.link[h].href;break}for(h=0;h<f.link.length;h++)if("replies"==f.link[h].rel&&"text/html"==f.link[h].type){f.link[h].title.split(" ");break}s="content"in f?f.content.$t:"summary"in f?f.summary.$t:"";a=s.indexOf("<img");b=s.indexOf('src="',a);c=s.indexOf('"',
b+5);d=s.substr(b+5,c-b-5);-1!=a&&-1!=b&&-1!=c&&""!=d&&(img[g]=d);0<=g&&16>=g&&(f='<li class="list-top-movie-item"><a class="list-top-movie-link" title="'+k+'" href="'+l+'"><div class="list-top-movie-item-thumb" style="background-image: url('+img[g]+')"></div><div class="list-top-movie-item-info"><span class="list-top-movie-item-vn">'+titvn(k)+'</span><span class="list-top-movie-item-en">'+titen(k)+'</span><span class="list-top-movie-item-view">'+altit(k)+"</span></div></a></li>",document.write(f))}document.write("")}
;
//]]>