function getCurrentYear(){var e=new Date;return e.getFullYear()}el=document.getElementById("current-year"),el.innerHTML=getCurrentYear();
function show(e){document.getElementById(e).style.display="block"}function hide(e){document.getElementById(e).style.display="none"}
$(window).on("hashchange",function(n){history.replaceState("",document.title,n.originalEvent.oldURL)});
//<![CDATA[
//Random Post
function showLucky(e){for(var t=e.feed,a=(t.entry||[],t.entry[0]),c=0;c<a.link.length;++c)"alternate"==a.link[c].rel&&(window.location=a.link[c].href)}function fetchLuck(e){script=document.createElement("script"),script.src="/feeds/posts/summary?start-index="+e+"&max-results=1&alt=json-in-script&callback=showLucky",script.type="text/javascript",document.getElementsByTagName("head")[0].appendChild(script)}function readLucky(e){var t=e.feed,a=parseInt(t.openSearch$totalResults.$t,10),c=Math.floor(Math.random()*a);c++,fetchLuck(c)}function feelingLucky(){var e=document.createElement("script");e.type="text/javascript",e.src="/feeds/posts/summary?max-results=0&alt=json-in-script&callback=readLucky",document.getElementsByTagName("head")[0].appendChild(e)}
// Multi Tab
!function(t){"use strict";var e=function(e,a){var n=this;n.element=e,n.$element=t(e),n.tabs=n.$element.children(),n.options=t.extend({},t.fn.mtabs.defaults,a),n.current_tab=0,n.init()};e.prototype={init:function(){var t=this;t.tabs.length&&(t.build(),t.buildTabMenu())},build:function(){var e=this,a=e.options,n=a.tab_text_el,s=a.container_class;e.tab_names=[],e.$wrapper=e.$element.wrapInner('<div class="'+s+'" />').find("."+s),e.tabs.wrapAll('<div class="'+a.tabs_container_class+'" />'),e.tabs.each(function(a,s){var i,r=t(s),l=n;i=r.find(l).filter(":first").hide().text(),e.tab_names.push(i)}),t.isFunction(a.onReady)&&a.onReady.call(e.element)},buildTabMenu:function(){for(var e,a=this,n=a.options,s=n.tabsmenu_el,i=a.tab_names,r="<"+s+' class="'+n.tabsmenu_class+'">',l=0,o=i.length,c=function(){var t=arguments;return n.tmpl.tabsmenu_tab.replace(/\{[0-9]\}/g,function(e){var a=Number(e.replace(/\D/g,""));return t[a]||""})};o>l;l++)r+=c(l+1,i[l]);r+="</"+s+">",a.$tabs_menu=t(r).prependTo(a.$wrapper),e=a.$tabs_menu.find(":first")[0].nodeName.toLowerCase(),a.$tabs_menu.on("click",e,function(e){var n=t(this),s=n.index();a.show(s),e.preventDefault()}).find(":first").trigger("click")},show:function(e){var a=this,n=a.options,s=n.active_tab_class;a.tabs.hide().filter(":eq("+e+")").show(),a.$tabs_menu.children().removeClass(s).filter(":eq("+e+")").addClass(s),t.isFunction(n.onTabSelect)&&e!==a.current_tab&&n.onTabSelect.call(a.element,e),a.current_tab=e},destroy:function(){var t=this,e=t.options.tab_text_el;t.$tabs_menu.remove(),t.tabs.unwrap().unwrap(),t.tabs.removeAttr("style"),t.tabs.children(e+":first").removeAttr("style"),t.$element.removeData("mtabs")}},t.fn.mtabs=function(a,n){return this.each(function(){var s,i=t(this),r=i.data("mtabs");s="object"==typeof a&&a,r||i.data("mtabs",r=new e(this,s)),"string"==typeof a&&r[a](n)})},t.fn.mtabs.defaults={container_class:"tabs",tabs_container_class:"tabs-content",active_tab_class:"active-tab",tab_text_el:"h1, h2, h3, h4, h5, h6",tabsmenu_class:"tabs-menu",tabsmenu_el:"ul",tmpl:{tabsmenu_tab:'<li class="tab-{0}"><span>{1}</span></li>'},onTabSelect:null}}(window.jQuery,window,document);
$("h1.title a,h2.title a").each(function(){var t=$(this).text().split(" ");t.length<2||(t[1]='<span class="secondWord">'+t[1]+"</span>",$(this).html(t.join(" ")))});
//]]>