/* 元のURL: https://gmail.com */
(function(){'use strict';var n=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},aa=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ba=aa(this),p=function(a,b){if(b)a:{var c=ba;a=a.split(".");for(var d=
0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&n(c,a,{configurable:!0,writable:!0,value:b})}},ca=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},q=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:ca(a)};throw Error(String(a)+" is not an iterable or ArrayLike");};
p("Symbol",function(a){if(a)return a;var b=function(f,k){this.g=f;n(this,"description",{configurable:!0,writable:!0,value:k})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
p("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");n(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return da(ca(this))}});return a});var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},r=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};p("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});
p("WeakMap",function(a){function b(){}function c(h){var l=typeof h;return l==="object"&&h!==null||l==="function"}function d(h){if(!r(h,f)){var l=new b;n(h,f,{value:l})}}function e(h){var l=Object[h];l&&(Object[h]=function(m){if(m instanceof b)return m;Object.isExtensible(m)&&d(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),l=Object.seal({}),m=new a([[h,2],[l,3]]);if(m.get(h)!=2||m.get(l)!=3)return!1;m.delete(h);m.set(l,4);return!m.has(h)&&m.get(l)==4}catch(B){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var k=0,g=function(h){this.g=(k+=Math.random()+1).toString();if(h){h=q(h);for(var l;!(l=h.next()).done;)l=l.value,this.set(l[0],l[1])}};g.prototype.set=function(h,l){if(!c(h))throw Error("Invalid WeakMap key");d(h);if(!r(h,f))throw Error("WeakMap key fail: "+h);h[f][this.g]=l;return this};g.prototype.get=function(h){return c(h)&&r(h,f)?h[f][this.g]:void 0};g.prototype.has=function(h){return c(h)&&r(h,f)&&r(h[f],this.g)};
g.prototype.delete=function(h){return c(h)&&r(h,f)&&r(h[f],this.g)?delete h[f][this.g]:!1};return g});
p("Map",function(a){if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),h=new a(q([[g,"s"]]));if(h.get(g)!="s"||h.size!=1||h.get({x:4})||h.set({x:4},"t")!=h||h.size!=2)return!1;var l=h.entries(),m=l.next();if(m.done||m.value[0]!=g||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=4||m.value[1]!="t"||!l.next().done?!1:!0}catch(B){return!1}}())return a;var b=new WeakMap,c=function(g){this[0]={};this[1]=
f();this.size=0;if(g){g=q(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}};c.prototype.set=function(g,h){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=h:(l.entry={next:this[1],v:this[1].v,head:this[1],key:g,value:h},l.list.push(l.entry),this[1].v.next=l.entry,this[1].v=l.entry,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.entry.v.next=
g.entry.next,g.entry.next.v=g.entry.v,g.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].v=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).entry};c.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=
function(g,h){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,g.call(h,m[1],m[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,h){var l=h&&typeof h;l=="object"||l=="function"?b.has(h)?l=b.get(h):(l=""+ ++k,b.set(h,l)):l="p_"+h;var m=g[0][l];if(m&&r(g[0],l))for(g=0;g<m.length;g++){var B=m[g];if(h!==h&&B.key!==B.key||h===B.key)return{id:l,list:m,index:g,entry:B}}return{id:l,list:m,index:-1,entry:void 0}},e=function(g,h){var l=g[1];return da(function(){if(l){for(;l.head!=
g[1];)l=l.v;for(;l.next!=l.head;)return l=l.next,{done:!1,value:h(l)};l=null}return{done:!0,value:void 0}})},f=function(){var g={};return g.v=g.next=g.head=g},k=0;return c});var ea=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};
p("Array.prototype.entries",function(a){return a?a:function(){return ea(this,function(b,c){return[b,c]})}});p("Array.prototype.keys",function(a){return a?a:function(){return ea(this,function(b){return b})}});p("Array.prototype.values",function(a){return a?a:function(){return ea(this,function(b,c){return c})}});
p("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var k=d[f];if(b.call(c,k,f,d)){b=k;break a}}b=void 0}return b}});
p("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(g){return g};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var k=0;!(f=b.next()).done;)e.push(c.call(d,f.value,k++))}else for(f=b.length,k=0;k<f;k++)e.push(c.call(d,b[k],k));return e}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var fa=fa||{},t=this||self,u=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"},ha=function(a,b,c){return a.call.apply(a.bind,arguments)},ia=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},v=function(a,b,c){v=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=
-1?ha:ia;return v.apply(null,arguments)},w=function(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.fa=function(d,e,f){for(var k=Array(arguments.length-2),g=2;g<arguments.length;g++)k[g-2]=arguments[g];return b.prototype[e].apply(d,k)}};var ja=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var ka={};var x=function(a){if(ka!==ka)throw Error("Bad secret");this.g=a};x.prototype.toString=function(){return this.g};new x("about:blank");new x("about:invalid#zClosurez");var la=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i,ma=[],na=function(){};oa(function(a){console.warn("A URL with content '"+a+"' was sanitized away.")});function oa(a){ma.indexOf(a)===-1&&ma.push(a);na=function(b){ma.forEach(function(c){c(b)})}};function y(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,y);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)}w(y,Error);y.prototype.name="CustomError";function z(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");y.call(this,c+a[d])}w(z,y);z.prototype.name="AssertionError";function pa(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new z(""+e,f||[]);}
var A=function(a,b,c){a||pa("",null,b,Array.prototype.slice.call(arguments,2))},qa=function(a,b){throw new z("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},C=function(a,b,c){if(typeof a!=="number"){var d=typeof a;pa("Expected number but got %s: %s.",[d!="object"?d:a?Array.isArray(a)?"array":d:"null",a],b,Array.prototype.slice.call(arguments,2))}return a};var ra=Array.prototype.indexOf?function(a,b){A(a.length!=null);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};function sa(a,b){b=ra(a,b);var c;if(c=b>=0)A(a.length!=null),Array.prototype.splice.call(a,b,1);return c};var D=function(a,b){this.name=a;this.value=b};D.prototype.toString=function(){return this.name};
var ta=new D("OFF",Infinity),ua=new D("SEVERE",1E3),va=new D("CONFIG",700),wa=new D("FINE",500),xa=function(){},ya,za=function(){},Aa=function(a,b){this.g=null;this.l=[];this.h=(b===void 0?null:b)||null;this.j=[];this.m={g:function(){return a}}},Ba=function(a){if(a.g)return a.g;if(a.h)return Ba(a.h);qa("Root logger has no level set.");return ta},Ca=function(a,b){for(;a;)a.l.forEach(function(c){c(b)}),a=a.h},Da=function(){this.entries={};var a=new Aa("");a.g=va;this.entries[""]=a},Ea,E=function(a,
b){var c=a.entries[b];if(c)return c;c=E(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var d=new Aa(b,c);a.entries[b]=d;c.j.push(d);return d},Fa=function(){Ea||(Ea=new Da);return Ea},Ga=function(a,b,c){var d;if(d=a)if(d=a&&b)b=b.value,d=a?Ba(E(Fa(),a.g())):ta,d=b>=d.value;d&&(a=E(Fa(),a.g()),typeof c==="function"&&c(),ya||(ya=new xa),c=new za,Ca(a,c))},F=function(a,b){a&&Ga(a,wa,b)};var G=function(){this.g=(typeof document=="undefined"?null:document)||{cookie:""}};
G.prototype.set=function(a,b,c){var d=!1;if(typeof c==="object"){var e=c.ha;d=c.ia||!1;var f=c.domain||void 0;var k=c.path||void 0;var g=c.ga}if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g===void 0&&(g=-1);this.g.cookie=a+"="+b+(f?";domain="+f:"")+(k?";path="+k:"")+(g<0?"":g==0?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+g*1E3)).toUTCString())+(d?";secure":"")+(e!=null?";samesite="+
e:"")};G.prototype.get=function(a,b){for(var c=a+"=",d=(this.g.cookie||"").split(";"),e=0,f;e<d.length;e++){f=ja(d[e]);if(f.lastIndexOf(c,0)==0)return f.slice(c.length);if(f==a)return""}return b};G.prototype.m=function(){for(var a=(this.g.cookie||"").split(";"),b=[],c=[],d,e,f=0;f<a.length;f++)e=ja(a[f]),d=e.indexOf("="),d==-1?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return c};var Ha=new G;var Ia=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};var H=function(){this.I=this.I;this.g=this.g};H.prototype.I=!1;H.prototype.dispose=function(){this.I||(this.I=!0,this.H())};H.prototype[Symbol.dispose]=function(){this.dispose()};H.prototype.H=function(){if(this.g)for(;this.g.length;)this.g.shift()()};var I=function(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1};I.prototype.h=function(){this.defaultPrevented=!0};var Ja=function(){if(!t.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{var c=function(){};t.addEventListener("test",c,b);t.removeEventListener("test",c,b)}catch(d){}return a}();var J=function(a,b){I.call(this,a?a.type:"");this.relatedTarget=this.g=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.j=null;a&&this.init(a,b)};w(J,I);
J.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.g=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==
void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.j=a;a.defaultPrevented&&J.P.h.call(this)};J.prototype.h=function(){J.P.h.call(this);var a=this.j;a.preventDefault?a.preventDefault():a.returnValue=!1};var K="closure_listenable_"+(Math.random()*1E6|0);var Ka=0;var La=function(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.M=e;this.key=++Ka;this.K=this.L=!1},L=function(a){a.K=!0;a.listener=null;a.proxy=null;a.src=null;a.M=null};var Ma="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Na(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ma.length;f++)c=Ma[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function M(a){this.src=a;this.g={};this.h=0}M.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var k=Oa(a,b,d,e);k>-1?(b=a[k],c||(b.L=!1)):(b=new La(b,this.src,f,!!d,e),b.L=c,a.push(b));return b};var Pa=function(a,b){var c=b.type;c in a.g&&sa(a.g[c],b)&&(L(b),a.g[c].length==0&&(delete a.g[c],a.h--))},Oa=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.K&&f.listener==b&&f.capture==!!c&&f.M==d)return e}return-1};var Qa="closure_lm_"+(Math.random()*1E6|0),Ra={},Sa=0,Ua=function(a,b,c,d,e){if(d&&d.once)Ta(a,b,c,d,e);else if(Array.isArray(b))for(var f=0;f<b.length;f++)Ua(a,b[f],c,d,e);else c=Va(c),a&&a[K]?(d=u(d)?!!d.capture:!!d,Wa(a),a.u.add(String(b),c,!1,d,e)):Xa(a,b,c,!1,d,e)},Xa=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=u(e)?!!e.capture:!!e,g=Ya(a);g||(a[Qa]=g=new M(a));c=g.add(b,c,d,k,f);if(!c.proxy){d=Za();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Ja||(e=k),e===void 0&&
(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent($a(b.toString()),d);else if(a.addListener&&a.removeListener)A(b==="change","MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Sa++}},Za=function(){var a=ab,b=function(c){return a.call(b.src,b.listener,c)};return b},Ta=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Ta(a,b[f],c,d,e);else c=Va(c),a&&a[K]?a.u.add(String(b),c,
!0,u(d)?!!d.capture:!!d,e):Xa(a,b,c,!0,d,e)},bb=function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)bb(a,b[f],c,d,e);else(d=u(d)?!!d.capture:!!d,c=Va(c),a&&a[K])?(a=a.u,b=String(b).toString(),b in a.g&&(f=a.g[b],c=Oa(f,c,d,e),c>-1&&(L(f[c]),A(f.length!=null),Array.prototype.splice.call(f,c,1),f.length==0&&(delete a.g[b],a.h--)))):a&&(a=Ya(a))&&(b=a.g[b.toString()],a=-1,b&&(a=Oa(b,c,d,e)),(c=a>-1?b[a]:null)&&cb(c))},cb=function(a){if(typeof a!=="number"&&a&&!a.K){var b=a.src;if(b&&b[K])Pa(b.u,
a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent($a(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Sa--;(c=Ya(b))?(Pa(c,a),c.h==0&&(c.src=null,b[Qa]=null)):L(a)}}},$a=function(a){return a in Ra?Ra[a]:Ra[a]="on"+a},ab=function(a,b){if(a.K)a=!0;else{b=new J(b,this);var c=a.listener,d=a.M||a.src;a.L&&cb(a);a=c.call(d,b)}return a},Ya=function(a){a=a[Qa];return a instanceof M?a:null},db="__closure_events_fn_"+(Math.random()*
1E9>>>0),Va=function(a){A(a,"Listener can not be null.");if(typeof a==="function")return a;A(a.handleEvent,"An object listener must have handleEvent method.");a[db]||(a[db]=function(b){return a.handleEvent(b)});return a[db]};var N=function(){H.call(this);this.u=new M(this);this.j=this;this.h=null};w(N,H);N.prototype[K]=!0;N.prototype.addEventListener=function(a,b,c,d){Ua(this,a,b,c,d)};N.prototype.removeEventListener=function(a,b,c,d){bb(this,a,b,c,d)};
N.prototype.dispatchEvent=function(a){Wa(this);var b=this.h;if(b){var c=[];for(var d=1;b;b=b.h)c.push(b),A(++d<1E3,"infinite loop")}b=this.j;d=a.type||a;if(typeof a==="string")a=new I(a,b);else if(a instanceof I)a.target=a.target||b;else{var e=a;a=new I(d,b);Na(a,e)}e=!0;var f;if(c)for(f=c.length-1;f>=0;f--){var k=a.g=c[f];e=O(k,d,!0,a)&&e}k=a.g=b;e=O(k,d,!0,a)&&e;e=O(k,d,!1,a)&&e;if(c)for(f=0;f<c.length;f++)k=a.g=c[f],e=O(k,d,!1,a)&&e;return e};
N.prototype.H=function(){N.P.H.call(this);if(this.u){var a=this.u,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,L(d[e]);delete a.g[c];a.h--}}this.h=null};var O=function(a,b,c,d){b=a.u.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var k=b[f];if(k&&!k.K&&k.capture==c){var g=k.listener,h=k.M||k.src;k.L&&Pa(a.u,k);e=g.call(h,d)!==!1&&e}}return e&&!d.defaultPrevented},Wa=function(a){A(a.u,"Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?")};var eb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),fb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(d>=0){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var P=function(){N.call(this);this.headers=new Map;this.A=!1;this.i=null;this.J=this.W=this.O="";this.B=this.U=this.N=this.T=!1;this.R=0;this.F=null;this.Z="";this.da=this.aa=!1;this.S=this.V=null};w(P,N);P.prototype.o=E(Fa(),"goog.net.XhrIo").m;var gb=/^https?$/i,hb=["POST","PUT"],ib=[];P.prototype.ba=function(){this.dispose();sa(ib,this)};P.prototype.setTrustToken=function(a){this.V=a};P.prototype.setAttributionReporting=function(a){this.S=a};
P.prototype.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.O+"; newUri="+a);b=b?b.toUpperCase():"GET";this.O=a;this.J="";this.W=b;this.T=!1;this.A=!0;this.i=new XMLHttpRequest;this.i.onreadystatechange=Ia(v(this.Y,this));this.da&&"onprogress"in this.i&&(this.i.onprogress=Ia(v(function(k){this.X(k,!0)},this)),this.i.upload&&(this.i.upload.onprogress=Ia(v(this.X,this))));try{F(this.o,Q(this,"Opening Xhr")),this.U=!0,this.i.open(b,String(a),
!0),this.U=!1}catch(k){F(this.o,Q(this,"Error opening Xhr: "+k.message));jb(this,k);return}a=c||"";c=new Map(this.headers);if(d)if(Object.getPrototypeOf(d)===Object.prototype)for(var e in d)c.set(e,d[e]);else if(typeof d.keys==="function"&&typeof d.get==="function"){e=q(d.keys());for(var f=e.next();!f.done;f=e.next())f=f.value,c.set(f,d.get(f))}else throw Error("Unknown input type for opt_headers: "+String(d));d=Array.from(c.keys()).find(function(k){return"content-type"==k.toLowerCase()});e=t.FormData&&
a instanceof t.FormData;!(ra(hb,b)>=0)||d||e||c.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=q(c);for(d=b.next();!d.done;d=b.next())c=q(d.value),d=c.next().value,c=c.next().value,this.i.setRequestHeader(d,c);this.Z&&(this.i.responseType=this.Z);"withCredentials"in this.i&&this.i.withCredentials!==this.aa&&(this.i.withCredentials=this.aa);if("setTrustToken"in this.i&&this.V)try{this.i.setTrustToken(this.V)}catch(k){F(this.o,Q(this,"Error SetTrustToken: "+k.message))}if("setAttributionReporting"in
this.i&&this.S)try{this.i.setAttributionReporting(this.S)}catch(k){F(this.o,Q(this,"Error SetAttributionReporting: "+k.message))}try{this.F&&(clearTimeout(this.F),this.F=null),this.R>0&&(F(this.o,Q(this,"Will abort after "+this.R+"ms if incomplete")),this.F=setTimeout(this.ea.bind(this),this.R)),F(this.o,Q(this,"Sending request")),this.N=!0,this.i.send(a),this.N=!1}catch(k){F(this.o,Q(this,"Send error: "+k.message)),jb(this,k)}};
P.prototype.ea=function(){typeof fa!="undefined"&&this.i&&(this.J="Timed out after "+this.R+"ms, aborting",F(this.o,Q(this,this.J)),this.dispatchEvent("timeout"),this.abort(8))};var jb=function(a,b){a.A=!1;a.i&&(a.B=!0,a.i.abort(),a.B=!1);a.J=b;kb(a);R(a)},kb=function(a){a.T||(a.T=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};
P.prototype.abort=function(){this.i&&this.A&&(F(this.o,Q(this,"Aborting")),this.A=!1,this.B=!0,this.i.abort(),this.B=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),R(this))};P.prototype.H=function(){this.i&&(this.A&&(this.A=!1,this.B=!0,this.i.abort(),this.B=!1),R(this,!0));P.P.H.call(this)};P.prototype.Y=function(){this.I||(this.U||this.N||this.B?lb(this):this.ca())};P.prototype.ca=function(){lb(this)};
var lb=function(a){if(a.A&&typeof fa!="undefined")if(a.N&&S(a)==4)setTimeout(a.Y.bind(a),0);else if(a.dispatchEvent("readystatechange"),S(a)==4){F(a.o,Q(a,"Request complete"));a.A=!1;try{if(mb(a))a.dispatchEvent("complete"),a.dispatchEvent("success");else{try{var b=S(a)>2?a.i.statusText:""}catch(c){F(a.o,"Can not get status: "+c.message),b=""}a.J=b+" ["+nb(a)+"]";kb(a)}}finally{R(a)}}};
P.prototype.X=function(a,b){A(a.type==="progress","goog.net.EventType.PROGRESS is of the same type as raw XHR progress.");this.dispatchEvent(ob(a,"progress"));this.dispatchEvent(ob(a,b?"downloadprogress":"uploadprogress"))};
var ob=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}},R=function(a,b){if(a.i){a.F&&(clearTimeout(a.F),a.F=null);var c=a.i;a.i=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=null}catch(d){(a=a.o)&&Ga(a,ua,"Problem encountered resetting onreadystatechange: "+d.message)}}};P.prototype.isActive=function(){return!!this.i};
var mb=function(a){var b=nb(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=b===0)a=String(a.O).match(eb)[1]||null,!a&&t.self&&t.self.location&&(a=t.self.location.protocol.slice(0,-1)),b=!gb.test(a?a.toLowerCase():"");c=b}return c},S=function(a){return a.i?a.i.readyState:0},nb=function(a){try{return S(a)>2?a.i.status:-1}catch(b){return-1}};
P.prototype.getResponseHeader=function(a){if(this.i&&S(this)==4)return a=this.i.getResponseHeader(a),a===null?void 0:a};P.prototype.getAllResponseHeaders=function(){return this.i&&S(this)>=2?this.i.getAllResponseHeaders()||"":""};var Q=function(a,b){return b+" ["+a.W+" "+a.O+" "+nb(a)+"]"};var T=function(a){this.g=this.D=this.l="";this.G=null;this.C=this.h="";this.m=!1;var b;a instanceof T?(this.m=a.m,pb(this,a.l),this.D=a.D,this.g=a.g,qb(this,a.G),U(this,a.h),rb(this,sb(a.j)),this.C=a.C):a&&(b=String(a).match(eb))?(this.m=!1,pb(this,b[1]||"",!0),this.D=V(b[2]||""),this.g=V(b[3]||"",!0),qb(this,b[4]),U(this,b[5]||"",!0),rb(this,b[6]||"",!0),this.C=V(b[7]||"")):(this.m=!1,this.j=new W(null,this.m))};
T.prototype.toString=function(){var a=[],b=this.l;b&&a.push(X(b,tb,!0),":");var c=this.g;if(c||b=="file")a.push("//"),(b=this.D)&&a.push(X(b,tb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.G,c!=null&&a.push(":",String(c));if(c=this.h)this.g&&c.charAt(0)!="/"&&a.push("/"),a.push(X(c,c.charAt(0)=="/"?ub:vb,!0));(c=this.j.toString())&&a.push("?",c);(c=this.C)&&a.push("#",X(c,wb));return a.join("")};
T.prototype.resolve=function(a){var b=new T(this),c=!!a.l;c?pb(b,a.l):c=!!a.D;c?b.D=a.D:c=!!a.g;c?b.g=a.g:c=a.G!=null;var d=a.h;if(c)qb(b,a.G);else if(c=!!a.h){if(d.charAt(0)!="/")if(this.g&&!this.h)d="/"+d;else{var e=b.h.lastIndexOf("/");e!=-1&&(d=b.h.slice(0,e+1)+d)}e=d;if(e==".."||e==".")d="";else if(e.indexOf("./")!=-1||e.indexOf("/.")!=-1){d=e.lastIndexOf("/",0)==0;e=e.split("/");for(var f=[],k=0;k<e.length;){var g=e[k++];g=="."?d&&k==e.length&&f.push(""):g==".."?((f.length>1||f.length==1&&f[0]!=
"")&&f.pop(),d&&k==e.length&&f.push("")):(f.push(g),d=!0)}d=f.join("/")}else d=e}c?U(b,d):c=a.j.toString()!=="";c?rb(b,sb(a.j)):c=!!a.C;c&&(b.C=a.C);return b};
var pb=function(a,b,c){a.l=c?V(b,!0):b;a.l&&(a.l=a.l.replace(/:$/,""))},qb=function(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.G=b}else a.G=null},U=function(a,b,c){a.h=c?V(b,!0):b;return a},rb=function(a,b,c){b instanceof W?(a.j=b,xb(a.j,a.m)):(c||(b=X(b,yb)),a.j=new W(b,a.m));return a},V=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},X=function(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,zb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},zb=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},tb=/[#\/\?@]/g,vb=/[#\?:]/g,ub=/[#\?]/g,yb=/[#\?@]/g,wb=/#/g,W=function(a,b){this.h=this.g=null;this.j=a||null;this.l=!!b},Y=function(a){a.g||(a.g=new Map,a.h=0,a.j&&fb(a.j,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};W.prototype.add=function(a,b){Y(this);this.j=null;a=Z(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h=C(this.h)+1;return this};
var Ab=function(a,b){Y(a);b=Z(a,b);a.g.has(b)&&(a.j=null,a.h=C(a.h)-a.g.get(b).length,a.g.delete(b))},Bb=function(a,b){Y(a);b=Z(a,b);return a.g.has(b)};W.prototype.forEach=function(a,b){Y(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};W.prototype.m=function(a){Y(this);var b=[];if(typeof a==="string")Bb(this,a)&&(b=b.concat(this.g.get(Z(this,a))));else{a=Array.from(this.g.values());for(var c=0;c<a.length;c++)b=b.concat(a[c])}return b};
W.prototype.set=function(a,b){Y(this);this.j=null;a=Z(this,a);Bb(this,a)&&(this.h=C(this.h)-this.g.get(a).length);this.g.set(a,[b]);this.h=C(this.h)+1;return this};W.prototype.get=function(a,b){if(!a)return b;a=this.m(a);return a.length>0?String(a[0]):b};
W.prototype.toString=function(){if(this.j)return this.j;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.m(d);for(var f=0;f<d.length;f++){var k=e;d[f]!==""&&(k+="="+encodeURIComponent(String(d[f])));a.push(k)}}return this.j=a.join("&")};
var sb=function(a){var b=new W;b.j=a.j;a.g&&(b.g=new Map(a.g),b.h=a.h);return b},Z=function(a,b){b=String(b);a.l&&(b=b.toLowerCase());return b},xb=function(a,b){b&&!a.l&&(Y(a),a.j=null,a.g.forEach(function(c,d){var e=d.toLowerCase();if(d!=e&&(Ab(this,d),Ab(this,e),c.length>0)){this.j=null;d=this.g;var f=d.set;e=Z(this,e);var k=c.length;if(k>0){for(var g=Array(k),h=0;h<k;h++)g[h]=c[h];k=g}else k=[];f.call(d,e,k);this.h=C(this.h)+c.length}},a));a.l=b};var Db=function(){this.h=void 0;this.g=null;Cb(this,0);window.addEventListener("load",this.m.bind(this))};
Db.prototype.l=function(a){if(this.g){a=a.target;var b;if(b=mb(a)){try{var c=a.i?a.i.responseText:""}catch(d){F(a.o,"Can not get responseText: "+d.message),c=""}b=c==="OK"}if(b){this.j();c=window.location;a=U(new T(window.location),"/ServiceLogin").toString();if(a instanceof x)if(a instanceof x)a=a.g;else throw Error("Unexpected type when unwrapping SafeUrl, got '"+a+"' of type '"+typeof a+"'");else(b=!la.test(a))&&na(a),a=b?void 0:a;a!==void 0&&(c.href=a)}else Cb(this,5E3)}};
var Cb=function(a,b){a.g=setTimeout(function(){if(a.g){var c=Ha.get("APISID");if(c===a.h)Cb(a,5E3);else{a.h=c;c=new T("/PassiveLoginProber");var d=(new T(window.location)).j;c=rb(c,d).toString();d=a.l.bind(a);var e=new P;ib.push(e);d&&(Wa(e),e.u.add("complete",d,!1,void 0,void 0));e.u.add("ready",e.ba,!0,void 0,void 0);e.send(c,void 0,void 0,void 0)}}},b)};Db.prototype.m=function(){document.addEventListener("submit",this.j.bind(this))};
Db.prototype.j=function(){this.g&&(clearTimeout(this.g),this.g=null)};new Db;}).call(this);


