/* 元のURL: https://g.page */
;this.gbar_={CONFIG:[[[0,"www.gstatic.com","og.qtm.en_US.QAG0_Ah8NaE.es5.O","co.jp","en","117",0,[4,2,".76.","","","824297427","0"],null,"3TcBaYD-FeC-0PEP-taJqQI",null,0,"og.qtm.oQT7yPxXZ5U.L.X.O","AA2YrTtUCcUdcKzHGml_MjZ-66Waf5hBOw","AA2YrTsWpsv9GgwDv--y86G7znhWprkKQw","",2,1,200,"JPN",null,null,"117","117",1,null,null,79508299,null,0,0],null,[1,0.1000000014901161,2,1],null,[0,0,0,null,"","","","",0,0,null,""],[1,1,"",1,1,0,1,1,0,0,null,1,0,null,0,1,null,null,0,0,0,"","","","","","",null,0,0,0,0,0,null,null,null,"rgba(32,33,36,1)","rgba(255,255,255,1)",0,0,1,null,null,null,0],null,null,["1","gci_91f30755d6a6b787dcc2a4062e6e9824.js","googleapis.client:gapi.iframes","","en"],null,null,null,null,["m;/_/scs/abc-static/_/js/k=gapi.gapi.en.wGQ1JnvbZsA.O/d=1/rs=AHpOoo_CQByDq4M_GLyNYLaxwBcABC_4uA/m=__features__","https://apis.google.com","","","","",null,1,"es_plusone_gc_20250903.0_p1","en",null,0],[0.009999999776482582,"co.jp","117",[null,"","0",null,1,5184000,null,null,"",null,null,null,null,null,0,null,1,null,1,0,0,0,null,null,0,0,null,0,0,0,0,0],null,null,null,0],[1,null,null,27043,117,"JPN","en","824297427.0",7,null,0,0,null,null,null,null,"",null,null,null,"3TcBaYD-FeC-0PEP-taJqQI",0,0,0,null,2,5,"pw",90,0,0,null,null,1,79508299,0,0],[[null,null,null,"https://www.gstatic.com/og/_/js/k=og.qtm.en_US.QAG0_Ah8NaE.es5.O/rt=j/m=q_dnp,q_sf,q_pc,qmd,qapid,qads,q_dg/exm=qaaw,qabr,qadd,qaid,qalo,qebr,qein,qhaw,qhawgm3,qhba,qhbr,qhbrgm3,qhch,qhchgm3,qhga,qhid,qhidgm3,qhin,qhlo,qhlogm3,qhmn,qhpc,qhsf,qhsfgm3,qhtt/d=1/ed=1/rs=AA2YrTtUCcUdcKzHGml_MjZ-66Waf5hBOw"],[null,null,null,"https://www.gstatic.com/og/_/ss/k=og.qtm.oQT7yPxXZ5U.L.X.O/m=q_sf,qmd/excm=qaaw,qabr,qadd,qaid,qalo,qebr,qein,qhaw,qhawgm3,qhba,qhbr,qhbrgm3,qhch,qhchgm3,qhga,qhid,qhidgm3,qhin,qhlo,qhlogm3,qhmn,qhpc,qhsf,qhsfgm3,qhtt/d=1/ed=1/ct=zgms/rs=AA2YrTsWpsv9GgwDv--y86G7znhWprkKQw"]]]],};this.gbar_=this.gbar_||{};(function(_){var window=this;
try{
_._F_toggles_initialize=function(a){(typeof globalThis!=="undefined"?globalThis:typeof self!=="undefined"?self:this)._F_toggles_gbar_=a||[]};(0,_._F_toggles_initialize)([]);
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ia,oa,qa,ua,wa,xa,Ka,La,eb,hb,jb,pb,lb,sb,xb,Kb,Lb,Mb,Nb,Ob,Wb,Xb,Yb,Zb;_.aa=function(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,_.aa);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b)};_.ba=function(a){a.Im=!0;return a};
_.ha=function(a){var b=a;if(ca(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(da(b)&&!Number.isSafeInteger(b))throw Error(String(b));return ea?BigInt(a):a=fa(a)?a?"1":"0":ca(a)?a.trim()||"0":String(a)};ia=function(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};_.ja=function(a){_.t.setTimeout(function(){throw a;},0)};
_.la=function(){return _.ka().toLowerCase().indexOf("webkit")!=-1};_.ka=function(){var a=_.t.navigator;return a&&(a=a.userAgent)?a:""};oa=function(a){if(!ma||!na)return!1;for(var b=0;b<na.brands.length;b++){var c=na.brands[b].brand;if(c&&c.indexOf(a)!=-1)return!0}return!1};_.pa=function(a){return _.ka().indexOf(a)!=-1};qa=function(){return ma?!!na&&na.brands.length>0:!1};_.ra=function(){return qa()?!1:_.pa("Opera")};_.sa=function(){return qa()?!1:_.pa("Trident")||_.pa("MSIE")};
_.ta=function(){return _.pa("Firefox")||_.pa("FxiOS")};_.va=function(){return _.pa("Safari")&&!(ua()||(qa()?0:_.pa("Coast"))||_.ra()||(qa()?0:_.pa("Edge"))||(qa()?oa("Microsoft Edge"):_.pa("Edg/"))||(qa()?oa("Opera"):_.pa("OPR"))||_.ta()||_.pa("Silk")||_.pa("Android"))};ua=function(){return qa()?oa("Chromium"):(_.pa("Chrome")||_.pa("CriOS"))&&!(qa()?0:_.pa("Edge"))||_.pa("Silk")};wa=function(){return ma?!!na&&!!na.platform:!1};xa=function(){return _.pa("iPhone")&&!_.pa("iPod")&&!_.pa("iPad")};
_.ya=function(){return xa()||_.pa("iPad")||_.pa("iPod")};_.za=function(){return wa()?na.platform==="macOS":_.pa("Macintosh")};_.Ba=function(a,b){return(0,_.Aa)(a,b)>=0};_.Ca=function(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b};_.Ga=function(a,b){_.Da||_.v in a||Ea(a,Fa);a[_.v]|=b};_.Ha=function(a,b){_.Da||_.v in a||Ea(a,Fa);a[_.v]=b};
_.Ja=function(a,b){return b===void 0?a.j!==Ia&&!!(2&(a.J[_.v]|0)):!!(2&b)&&a.j!==Ia};Ka=function(a){return a};La=function(a,b){a.__closure__error__context__984382||(a.__closure__error__context__984382={});a.__closure__error__context__984382.severity=b};_.Ma=function(a){a=Error(a);La(a,"warning");return a};_.Oa=function(a,b){if(a!=null){var c;var d=(c=Na)!=null?c:Na={};c=d[a]||0;c>=b||(d[a]=c+1,a=Error(),La(a,"incident"),_.ja(a))}};
_.Qa=function(a){if(typeof a!=="boolean")throw Error("y`"+_.Pa(a)+"`"+a);return a};_.Ra=function(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a};_.Ta=function(a){if(!(0,_.Sa)(a))throw _.Ma("enum");return a|0};_.Ua=function(a){return a==null?a:(0,_.Sa)(a)?a|0:void 0};_.Va=function(a){if(typeof a!=="number")throw _.Ma("int32");if(!(0,_.Sa)(a))throw _.Ma("int32");return a|0};_.Wa=function(a){if(a!=null&&typeof a!=="string")throw Error();return a};
_.Xa=function(a){return a==null||typeof a==="string"?a:void 0};_.$a=function(a,b,c){if(a!=null&&a[_.Ya]===_.Za)return a;if(Array.isArray(a)){var d=a[_.v]|0;c=d|c&32|c&2;c!==d&&_.Ha(a,c);return new b(a)}};_.cb=function(a){var b=_.ab(_.bb);return b?a[b]:void 0};eb=function(a,b){b<100||_.Oa(db,1)};
hb=function(a,b,c,d){var e=d!==void 0;d=!!d;var f=_.ab(_.bb),g;!e&&_.Da&&f&&(g=a[f])&&g.Id(eb);f=[];var h=a.length;g=4294967295;var k=!1,m=!!(b&64),n=m?b&128?0:-1:void 0;if(!(b&1)){var p=h&&a[h-1];p!=null&&typeof p==="object"&&p.constructor===Object?(h--,g=h):p=void 0;if(m&&!(b&128)&&!e){k=!0;var q;g=((q=fb)!=null?q:Ka)(g-n,n,a,p,void 0)+n}}b=void 0;for(q=0;q<h;q++){var r=a[q];if(r!=null&&(r=c(r,d))!=null)if(m&&q>=g){var u=q-n,w=void 0;((w=b)!=null?w:b={})[u]=r}else f[q]=r}if(p)for(var A in p)h=p[A],
h!=null&&(h=c(h,d))!=null&&(q=+A,r=void 0,m&&!Number.isNaN(q)&&(r=q+n)<g?f[r]=h:(q=void 0,((q=b)!=null?q:b={})[A]=h));b&&(k?f.push(b):f[g]=b);e&&_.ab(_.bb)&&(a=_.cb(a))&&"function"==typeof _.gb&&a instanceof _.gb&&(f[_.bb]=a.i());return f};
jb=function(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(0,_.ib)(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[_.v]|0;return a.length===0&&b&1?void 0:hb(a,b,jb)}if(a!=null&&a[_.Ya]===_.Za)return lb(a);if("function"==typeof _.mb&&a instanceof _.mb)return a.j();return}return a};pb=function(a,b){if(b){fb=b==null||b===Ka||b[nb]!==ob?Ka:b;try{return lb(a)}finally{fb=void 0}}return lb(a)};
lb=function(a){a=a.J;return hb(a,a[_.v]|0,jb)};_.x=function(a,b,c){return _.qb(a,b,c,2048)};
_.qb=function(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("z");e=a[_.v]|0;if(rb&&1&e)throw Error("A");2048&e&&!(2&e)&&sb();if(e&256)throw Error("B");if(e&64)return(e|d)!==e&&_.Ha(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("C");a:{c=a;e|=64;var f=c.length;if(f){var g=f-1,h=c[g];if(h!=null&&typeof h==="object"&&h.constructor===Object){b=e&128?0:-1;g-=b;if(g>=1024)throw Error("E");for(var k in h)f=+k,f<g&&
(c[f+b]=h[k],delete h[k]);e=e&-16760833|(g&1023)<<14;break a}}if(b){k=Math.max(b,f-(e&128?0:-1));if(k>1024)throw Error("F");e=e&-16760833|(k&1023)<<14}}}_.Ha(a,e|64|d);return a};sb=function(){if(rb)throw Error("D");_.Oa(tb,5)};
xb=function(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[_.v]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=_.ub(a,c,!1,b&&!(c&16)):(_.Ga(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[_.Ya]===_.Za)return b=a.J,c=b[_.v]|0,_.Ja(a,c)?a:_.vb(a,b,c)?_.wb(a,b):_.ub(b,c);if("function"==typeof _.mb&&a instanceof _.mb)return a};_.wb=function(a,b,c){a=new a.constructor(b);c&&(a.j=Ia);a.o=Ia;return a};
_.ub=function(a,b,c,d){d!=null||(d=!!(34&b));a=hb(a,b,xb,d);d=32;c&&(d|=2);b=b&16769217|d;_.Ha(a,b);return a};_.zb=function(a){var b=a.J,c=b[_.v]|0;return _.Ja(a,c)?_.vb(a,b,c)?_.wb(a,b,!0):new a.constructor(_.ub(b,c,!1)):a};_.Ab=function(a){if(a.j!==Ia)return!1;var b=a.J;b=_.ub(b,b[_.v]|0);_.Ga(b,2048);a.J=b;a.j=void 0;a.o=void 0;return!0};_.Bb=function(a){if(!_.Ab(a)&&_.Ja(a,a.J[_.v]|0))throw Error();};_.Cb=function(a,b){b===void 0&&(b=a[_.v]|0);b&32&&!(b&4096)&&_.Ha(a,b|4096)};
_.vb=function(a,b,c){return c&2?!0:c&32&&!(c&4096)?(_.Ha(b,c|2),a.j=Ia,!0):!1};_.Db=function(a,b,c,d,e){var f=c+(e?0:-1),g=a.length-1;if(g>=1+(e?0:-1)&&f>=g){var h=a[g];if(h!=null&&typeof h==="object"&&h.constructor===Object)return h[c]=d,b}if(f<=g)return a[f]=d,b;if(d!==void 0){var k;g=((k=b)!=null?k:b=a[_.v]|0)>>14&1023||536870912;c>=g?d!=null&&(f={},a[g+(e?0:-1)]=(f[c]=d,f)):a[f]=d}return b};
_.Fb=function(a,b,c,d,e){var f=!1;d=_.Eb(a,d,e,function(g){var h=_.$a(g,c,b);f=h!==g&&h!=null;return h});if(d!=null)return f&&!_.Ja(d)&&_.Cb(a,b),d};_.Gb=function(){var a=function(){throw Error();};Object.setPrototypeOf(a,a.prototype);return a};_.Hb=function(a,b){return a!=null?!!a:!!b};_.y=function(a,b){b==void 0&&(b="");return a!=null?a:b};_.Ib=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};_.Jb=function(a){for(var b in a)return!1;return!0};
Kb=typeof Object.create=="function"?Object.create:function(a){var b=function(){};b.prototype=a;return new b};Lb=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
Mb=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("a");};Nb=Mb(this);Ob="Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" ");Nb.BigInt64Array&&(Ob.push("BigInt64"),Ob.push("BigUint64"));
var Qb=function(a,b){if(b)for(var c=0;c<Ob.length;c++)Pb(Ob[c]+"Array.prototype."+a,b)},Rb=function(a,b){b&&Pb(a,b)},Pb=function(a,b){var c=Nb;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&Lb(c,a,{configurable:!0,writable:!0,value:b})},Sb;
if(typeof Object.setPrototypeOf=="function")Sb=Object.setPrototypeOf;else{var Tb;a:{var Ub={a:!0},Vb={};try{Vb.__proto__=Ub;Tb=Vb.a;break a}catch(a){}Tb=!1}Sb=Tb?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("b`"+a);return a}:null}Wb=Sb;
_.z=function(a,b){a.prototype=Kb(b.prototype);a.prototype.constructor=a;if(Wb)Wb(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.X=b.prototype};Xb=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};
_.B=function(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:Xb(a)};throw Error("c`"+String(a));};Yb=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};Zb=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("d");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Yb(d,e)&&(a[e]=d[e])}return a};
Rb("Object.assign",function(a){return a||Zb});Rb("globalThis",function(a){return a||Nb});Rb("Reflect.setPrototypeOf",function(a){return a?a:Wb?function(b,c){try{return Wb(b,c),!0}catch(d){return!1}}:null});
Rb("Symbol",function(a){if(a)return a;var b=function(f,g){this.i=f;Lb(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.i};var c="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("g");return new b(c+(f||"")+"_"+d++,f)};return e});Rb("Symbol.iterator",function(a){if(a)return a;a=Symbol("h");Lb(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $b(Xb(this))}});return a});
var $b=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};
Rb("Promise",function(a){function b(){this.i=null}function c(g){return g instanceof e?g:new e(function(h){h(g)})}if(a)return a;b.prototype.j=function(g){if(this.i==null){this.i=[];var h=this;this.o(function(){h.A()})}this.i.push(g)};var d=Nb.setTimeout;b.prototype.o=function(g){d(g,0)};b.prototype.A=function(){for(;this.i&&this.i.length;){var g=this.i;this.i=[];for(var h=0;h<g.length;++h){var k=g[h];g[h]=null;try{k()}catch(m){this.v(m)}}}this.i=null};b.prototype.v=function(g){this.o(function(){throw g;
})};var e=function(g){this.i=0;this.o=void 0;this.j=[];this.C=!1;var h=this.v();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.v=function(){function g(m){return function(n){k||(k=!0,m.call(h,n))}}var h=this,k=!1;return{resolve:g(this.Y),reject:g(this.A)}};e.prototype.Y=function(g){if(g===this)this.A(new TypeError("i"));else if(g instanceof e)this.M(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.K(g):this.B(g)}};e.prototype.K=
function(g){var h=void 0;try{h=g.then}catch(k){this.A(k);return}typeof h=="function"?this.N(h,g):this.B(g)};e.prototype.A=function(g){this.D(2,g)};e.prototype.B=function(g){this.D(1,g)};e.prototype.D=function(g,h){if(this.i!=0)throw Error("j`"+g+"`"+h+"`"+this.i);this.i=g;this.o=h;this.i===2&&this.L();this.F()};e.prototype.L=function(){var g=this;d(function(){if(g.G()){var h=Nb.console;typeof h!=="undefined"&&h.error(g.o)}},1)};e.prototype.G=function(){if(this.C)return!1;var g=Nb.CustomEvent,h=Nb.Event,
k=Nb.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=Nb.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.o;return k(g)};e.prototype.F=function(){if(this.j!=null){for(var g=0;g<this.j.length;++g)f.j(this.j[g]);this.j=null}};var f=new b;e.prototype.M=function(g){var h=this.v();g.Gd(h.resolve,h.reject)};
e.prototype.N=function(g,h){var k=this.v();try{g.call(h,k.resolve,k.reject)}catch(m){k.reject(m)}};e.prototype.then=function(g,h){function k(q,r){return typeof q=="function"?function(u){try{m(q(u))}catch(w){n(w)}}:r}var m,n,p=new e(function(q,r){m=q;n=r});this.Gd(k(g,m),k(h,n));return p};e.prototype.catch=function(g){return this.then(void 0,g)};e.prototype.Gd=function(g,h){function k(){switch(m.i){case 1:g(m.o);break;case 2:h(m.o);break;default:throw Error("k`"+m.i);}}var m=this;this.j==null?f.j(k):
this.j.push(k);this.C=!0};e.resolve=c;e.reject=function(g){return new e(function(h,k){k(g)})};e.race=function(g){return new e(function(h,k){for(var m=_.B(g),n=m.next();!n.done;n=m.next())c(n.value).Gd(h,k)})};e.all=function(g){var h=_.B(g),k=h.next();return k.done?c([]):new e(function(m,n){function p(u){return function(w){q[u]=w;r--;r==0&&m(q)}}var q=[],r=0;do q.push(void 0),r++,c(k.value).Gd(p(q.length-1),n),k=h.next();while(!k.done)})};return e});
var ac=function(a,b,c){if(a==null)throw new TypeError("l`"+c);if(b instanceof RegExp)throw new TypeError("m`"+c);return a+""};Rb("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=ac(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var g=0;g<f&&c<e;)if(d[c++]!=b[g++])return!1;return g>=f}});Rb("Object.setPrototypeOf",function(a){return a||Wb});Rb("Symbol.dispose",function(a){return a?a:Symbol("n")});
Rb("WeakMap",function(a){function b(){}function c(k){var m=typeof k;return m==="object"&&k!==null||m==="function"}function d(k){if(!Yb(k,f)){var m=new b;Lb(k,f,{value:m})}}function e(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),n=new a([[k,2],[m,3]]);if(n.get(k)!=2||n.get(m)!=3)return!1;n.delete(k);n.set(m,4);return!n.has(k)&&n.get(m)==4}catch(p){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var g=0,h=function(k){this.i=(g+=Math.random()+1).toString();if(k){k=_.B(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}};h.prototype.set=function(k,m){if(!c(k))throw Error("o");d(k);if(!Yb(k,f))throw Error("p`"+k);k[f][this.i]=m;return this};h.prototype.get=function(k){return c(k)&&Yb(k,f)?k[f][this.i]:void 0};h.prototype.has=function(k){return c(k)&&Yb(k,f)&&Yb(k[f],this.i)};h.prototype.delete=function(k){return c(k)&&
Yb(k,f)&&Yb(k[f],this.i)?delete k[f][this.i]:!1};return h});
Rb("Map",function(a){if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(_.B([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=4||n.value[1]!="t"||!m.next().done?!1:!0}catch(p){return!1}}())return a;var b=new WeakMap,c=function(h){this[0]={};this[1]=
f();this.size=0;if(h){h=_.B(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};c.prototype.set=function(h,k){h=h===0?0:h;var m=d(this,h);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this[1],wb:this[1].wb,head:this[1],key:h,value:k},m.list.push(m.entry),this[1].wb.next=m.entry,this[1].wb=m.entry,this.size++);return this};c.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],h.entry.wb.next=
h.entry.next,h.entry.next.wb=h.entry.wb,h.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].wb=f();this.size=0};c.prototype.has=function(h){return!!d(this,h).entry};c.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};c.prototype.entries=function(){return e(this,function(h){return[h.key,h.value]})};c.prototype.keys=function(){return e(this,function(h){return h.key})};c.prototype.values=function(){return e(this,function(h){return h.value})};c.prototype.forEach=
function(h,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,h.call(k,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(h,k){var m=k&&typeof k;m=="object"||m=="function"?b.has(k)?m=b.get(k):(m=""+ ++g,b.set(k,m)):m="p_"+k;var n=h[0][m];if(n&&Yb(h[0],m))for(h=0;h<n.length;h++){var p=n[h];if(k!==k&&p.key!==p.key||k===p.key)return{id:m,list:n,index:h,entry:p}}return{id:m,list:n,index:-1,entry:void 0}},e=function(h,k){var m=h[1];return $b(function(){if(m){for(;m.head!=
h[1];)m=m.wb;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})},f=function(){var h={};return h.wb=h.next=h.head=h},g=0;return c});
Rb("Set",function(a){if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var c=Object.seal({x:4}),d=new a(_.B([c]));if(!d.has(c)||d.size!=1||d.add(c)!=d||d.size!=1||d.add({x:4})!=d||d.size!=2)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=e.next();return f.done||f.value[0]==c||f.value[0].x!=4||f.value[1]!=f.value[0]?!1:e.next().done}catch(g){return!1}}())return a;var b=function(c){this.i=new Map;if(c){c=
_.B(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.i.size};b.prototype.add=function(c){c=c===0?0:c;this.i.set(c,c);this.size=this.i.size;return this};b.prototype.delete=function(c){c=this.i.delete(c);this.size=this.i.size;return c};b.prototype.clear=function(){this.i.clear();this.size=0};b.prototype.has=function(c){return this.i.has(c)};b.prototype.entries=function(){return this.i.entries()};b.prototype.values=function(){return this.i.values()};b.prototype.keys=b.prototype.values;
b.prototype[Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.i.forEach(function(f){return c.call(d,f,f,e)})};return b});Rb("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});
Rb("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Yb(b,d)&&c.push([d,b[d]]);return c}});Rb("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});Rb("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});Rb("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});Rb("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});
Rb("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});Rb("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});Rb("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
Rb("String.prototype.includes",function(a){return a?a:function(b,c){return ac(this,b,"includes").indexOf(b,c||0)!==-1}});var bc=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};Rb("Array.prototype.entries",function(a){return a?a:function(){return bc(this,function(b,c){return[b,c]})}});
Rb("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});Rb("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});Rb("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Yb(b,d)&&c.push(b[d]);return c}});
Rb("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});Rb("Array.prototype.keys",function(a){return a?a:function(){return bc(this,function(b){return b})}});Rb("Array.prototype.values",function(a){return a?a:function(){return bc(this,function(b,c){return c})}});
Rb("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;c<0&&(c=Math.max(0,e+c));if(d==null||d>e)d=e;d=Number(d);d<0&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});Qb("fill",function(a){return a?a:Array.prototype.fill});Rb("Promise.prototype.finally",function(a){return a?a:function(b){return this.then(function(c){return Promise.resolve(b()).then(function(){return c})},function(c){return Promise.resolve(b()).then(function(){throw c;})})}});
Rb("Array.prototype.flat",function(a){return a?a:function(b){b=b===void 0?1:b;var c=[];Array.prototype.forEach.call(this,function(d){Array.isArray(d)&&b>0?(d=Array.prototype.flat.call(d,b-1),c.push.apply(c,d)):c.push(d)});return c}});var ec,fc,jc,kc;_.cc=_.cc||{};_.t=this||self;ec=function(a,b){var c=_.dc("WIZ_global_data.oxN3nb");a=c&&c[a];return a!=null?a:b};fc=_.t._F_toggles_gbar_||[];_.dc=function(a,b){a=a.split(".");b=b||_.t;for(var c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b};_.Pa=function(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"};_.hc=function(a){var b=typeof a;return b=="object"&&a!=null||b=="function"};_.ic="closure_uid_"+(Math.random()*1E9>>>0);
jc=function(a,b,c){return a.call.apply(a.bind,arguments)};kc=function(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};_.C=function(a,b,c){_.C=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?jc:kc;return _.C.apply(null,arguments)};
_.lc=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};_.D=function(a,b){a=a.split(".");for(var c=_.t,d;a.length&&(d=a.shift());)a.length||b===void 0?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};_.ab=function(a){return a};
_.F=function(a,b){function c(){}c.prototype=b.prototype;a.X=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.zm=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}};_.F(_.aa,Error);_.aa.prototype.name="CustomError";var mc=!!(fc[0]>>15&1),nc=!!(fc[0]&1024),oc=!!(fc[0]>>16&1),pc=!!(fc[0]&128);var ma=mc?oc:ec(610401301,!1),rb=mc?nc||!pc:ec(748402147,!0);_.rc=_.ba(function(a){return a!==null&&a!==void 0});var da=_.ba(function(a){return typeof a==="number"}),ca=_.ba(function(a){return typeof a==="string"}),fa=_.ba(function(a){return typeof a==="boolean"});var ea=typeof _.t.BigInt==="function"&&typeof _.t.BigInt(0)==="bigint";var vc,sc,wc,tc;_.ib=_.ba(function(a){return ea?a>=sc&&a<=tc:a[0]==="-"?ia(a,vc):ia(a,wc)});vc=Number.MIN_SAFE_INTEGER.toString();sc=ea?BigInt(Number.MIN_SAFE_INTEGER):void 0;wc=Number.MAX_SAFE_INTEGER.toString();tc=ea?BigInt(Number.MAX_SAFE_INTEGER):void 0;_.xc=typeof Uint8Array.prototype.slice==="function";_.yc=typeof TextDecoder!=="undefined";_.zc=typeof String.prototype.isWellFormed==="function";_.Ac=typeof TextEncoder!=="undefined";_.Bc=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var na,Cc=_.t.navigator;na=Cc?Cc.userAgentData||null:null;_.Aa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.Dc=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=typeof a==="string"?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
_.Ec=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=typeof a==="string"?a.split(""):a,h=0;h<d;h++)if(h in g){var k=g[h];b.call(c,k,h,a)&&(e[f++]=k)}return e};_.Fc=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=typeof a==="string"?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};
_.Gc=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};_.Hc=function(a){_.Hc[" "](a);return a};_.Hc[" "]=function(){};var Uc;_.Ic=_.ra();_.Jc=_.sa();_.Kc=_.pa("Edge");_.Lc=_.pa("Gecko")&&!(_.la()&&!_.pa("Edge"))&&!(_.pa("Trident")||_.pa("MSIE"))&&!_.pa("Edge");_.Mc=_.la()&&!_.pa("Edge");_.Nc=_.za();_.Oc=wa()?na.platform==="Windows":_.pa("Windows");_.Pc=wa()?na.platform==="Android":_.pa("Android");_.Qc=xa();_.Rc=_.pa("iPad");_.Sc=_.pa("iPod");_.Tc=_.ya();
a:{var Vc="",Wc=function(){var a=_.ka();if(_.Lc)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.Kc)return/Edge\/([\d\.]+)/.exec(a);if(_.Jc)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Mc)return/WebKit\/(\S+)/.exec(a);if(_.Ic)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Wc&&(Vc=Wc?Wc[1]:"");if(_.Jc){var Xc,Yc=_.t.document;Xc=Yc?Yc.documentMode:void 0;if(Xc!=null&&Xc>parseFloat(Vc)){Uc=String(Xc);break a}}Uc=Vc}_.Zc=Uc;_.$c=_.ta();_.ad=xa()||_.pa("iPod");_.bd=_.pa("iPad");_.dd=_.pa("Android")&&!(ua()||_.ta()||_.ra()||_.pa("Silk"));_.ed=ua();_.fd=_.va()&&!_.ya();_.gd=typeof Uint8Array!=="undefined";_.hd=!_.Jc&&typeof btoa==="function";var id,db,tb,nb;_.Da=typeof Symbol==="function"&&typeof Symbol()==="symbol";id=_.Ca("jas",void 0,!0);_.bb=_.Ca(void 0,Symbol());_.jd=_.Ca(void 0,"0ub");db=_.Ca(void 0,"0ubs");_.kd=_.Ca(void 0,"0ubsb");tb=_.Ca(void 0,"0actk");_.Ya=_.Ca("m_m","Nm",!0);nb=_.Ca(void 0,"vps");_.ld=_.Ca();var Fa,Ea,nd;Fa={Xj:{value:0,configurable:!0,writable:!0,enumerable:!1}};Ea=Object.defineProperties;_.v=_.Da?id:"Xj";nd=[];_.Ha(nd,7);_.md=Object.freeze(nd);var Ia;_.Za={};Ia={};_.od=Object.freeze({});var ob={};var Na=void 0;_.pd=typeof BigInt==="function"?BigInt.asIntN:void 0;_.qd=Number.isSafeInteger;_.Sa=Number.isFinite;_.rd=Math.trunc;var fb;_.sd=_.ha(0);_.td={};_.ud=function(a,b,c,d,e){b=_.Eb(a.J,b,c,e);if(b!==null||d&&a.o!==Ia)return b};_.Eb=function(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),f=a.length-1;if(!(f<1+(c?0:-1))){if(e>=f){var g=a[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){c=g[b];var h=!0}else if(e===f)c=g;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return h?g[b]=d:a[e]=d,d}return c}};_.vd=function(a,b,c,d){_.Bb(a);var e=a.J;_.Db(e,e[_.v]|0,b,c,d);return a};
_.H=function(a,b,c,d){var e=a.J,f=e[_.v]|0;b=_.Fb(e,f,b,c,d);if(b==null)return b;f=e[_.v]|0;if(!_.Ja(a,f)){var g=_.zb(b);g!==b&&(_.Ab(a)&&(e=a.J,f=e[_.v]|0),b=g,f=_.Db(e,f,c,b,d),_.Cb(e,f))}return b};_.I=function(a,b,c){c==null&&(c=void 0);_.vd(a,b,c);c&&!_.Ja(c)&&_.Cb(a.J);return a};_.wd=function(a,b,c,d){return _.Ua(_.ud(a,b,c,d))};_.J=function(a,b,c,d){c=c===void 0?!1:c;var e;return(e=_.Ra(_.ud(a,b,d)))!=null?e:c};
_.K=function(a,b,c,d){c=c===void 0?"":c;var e;return(e=_.Xa(_.ud(a,b,d)))!=null?e:c};_.L=function(a,b,c){return _.Xa(_.ud(a,b,c,_.td))};_.M=function(a,b,c,d){return _.vd(a,b,c==null?c:_.Qa(c),d)};_.N=function(a,b,c){return _.vd(a,b,c==null?c:_.Va(c))};_.O=function(a,b,c,d){return _.vd(a,b,_.Wa(c),d)};_.P=function(a,b,c,d){return _.vd(a,b,c==null?c:_.Ta(c),d)};_.Q=function(a,b,c){this.J=_.x(a,b,c)};_.Q.prototype.toJSON=function(){return pb(this)};_.Q.prototype.va=function(a){return JSON.stringify(pb(this,a))};_.Q.prototype[_.Ya]=_.Za;_.Q.prototype.toString=function(){return this.J.toString()};_.xd=_.Gb();_.yd=_.Gb();_.zd=_.Gb();_.Ad=Symbol();var Bd=function(a){this.J=_.x(a)};_.z(Bd,_.Q);_.Cd=function(a){this.J=_.x(a)};_.z(_.Cd,_.Q);_.Cd.prototype.rd=function(a){return _.N(this,3,a)};_.Dd=function(a){this.J=_.x(a)};_.z(_.Dd,_.Q);_.R=function(){this.Aa=this.Aa;this.Y=this.Y};_.R.prototype.Aa=!1;_.R.prototype.isDisposed=function(){return this.Aa};_.R.prototype.dispose=function(){this.Aa||(this.Aa=!0,this.P())};_.R.prototype[Symbol.dispose]=function(){this.dispose()};_.R.prototype.P=function(){if(this.Y)for(;this.Y.length;)this.Y.shift()()};var Ed=function(a){_.R.call(this);this.o=a;this.i=[];this.j={}};_.z(Ed,_.R);Ed.prototype.resolve=function(a){var b=this.o;a=a.split(".");for(var c=a.length,d=0;d<c;++d)if(b[a[d]])b=b[a[d]];else return null;return b instanceof Function?b:null};Ed.prototype.tb=function(){for(var a=this.i.length,b=this.i,c=[],d=0;d<a;++d){var e=b[d].i(),f=this.resolve(e);if(f&&f!=this.j[e])try{b[d].tb(f)}catch(g){}else c.push(b[d])}this.i=c.concat(b.slice(a))};var Fd=function(a){_.R.call(this);this.o=a;this.A=this.i=null;this.v=0;this.B={};this.j=!1;a=window.navigator.userAgent;a.indexOf("MSIE")>=0&&a.indexOf("Trident")>=0&&(a=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a))&&a[1]&&parseFloat(a[1])<9&&(this.j=!0)};_.z(Fd,_.R);Fd.prototype.C=function(a,b){this.i=b;this.A=a;b.preventDefault?b.preventDefault():b.returnValue=!1};_.Hd=function(a){this.J=_.x(a)};_.z(_.Hd,_.Q);var Id=function(a){this.J=_.x(a)};_.z(Id,_.Q);var Kd=function(){var a=Jd;this.i=null;_.J(a,4,!0)};Kd.prototype.log=function(a,b,c){c=c===void 0?new _.Cd:c;_.Ld(this,a,98,c)};_.Ld=function(a,b,c,d){c=c===void 0?98:c;d=d===void 0?new _.Cd:d;if(a.i){var e=new Bd;_.O(e,1,b.message);_.O(e,2,b.stack);_.N(e,3,b.lineNumber);_.P(e,5,1);_.I(d,40,e);a.i.log(c,d)}};_.Md=function(a){this.i=a;this.j=void 0;this.o=[]};_.Md.prototype.then=function(a,b,c){this.o.push(new Nd(a,b,c));Od(this)};_.Md.prototype.resolve=function(a){if(this.i!==void 0||this.j!==void 0)throw Error("J");this.i=a;Od(this)};_.Md.prototype.reject=function(a){if(this.i!==void 0||this.j!==void 0)throw Error("J");this.j=a;Od(this)};var Od=function(a){if(a.o.length>0){var b=a.i!==void 0,c=a.j!==void 0;if(b||c){b=b?a.v:a.A;c=a.o;a.o=[];try{_.Dc(c,b,a)}catch(d){console.error(d)}}}};
_.Md.prototype.v=function(a){a.j&&a.j.call(a.i,this.i)};_.Md.prototype.A=function(a){a.o&&a.o.call(a.i,this.j)};var Nd=function(a,b,c){this.j=a;this.o=b;this.i=c};_.Pd=function(a){var b="Yb";if(a.Yb&&a.hasOwnProperty(b))return a.Yb;b=new a;return a.Yb=b};_.S=function(){this.v=new _.Md;this.i=new _.Md;this.D=new _.Md;this.B=new _.Md;this.C=new _.Md;this.A=new _.Md;this.o=new _.Md;this.j=new _.Md;this.F=new _.Md;this.G=new _.Md};_.l=_.S.prototype;_.l.aj=function(){return this.v};_.l.jj=function(){return this.i};_.l.tj=function(){return this.D};_.l.ij=function(){return this.B};_.l.qj=function(){return this.C};_.l.fj=function(){return this.A};_.l.Ui=function(){return this.o};_.l.Ti=function(){return this.j};_.l.kj=function(){return this.F};_.S.i=function(){return _.Pd(_.S)};var Qd=function(a){this.J=_.x(a)};_.z(Qd,_.Q);_.Sd=function(){return _.H(_.Rd,_.Dd,5)};var Td;window.gbar_&&window.gbar_.CONFIG?Td=window.gbar_.CONFIG[0]||{}:Td=[];_.Rd=new Qd(Td);var Jd;Jd=_.H(_.Rd,Id,3)||new Id;_.Ud=new Kd;_.D("gbar_._DumpException",function(a){_.Ud?_.Ud.log(a):console.error(a)});_.Vd=new Fd(_.Ud);_.Wd=function(){this.i={};this.j={}};_.Yd=function(a,b){var c=_.Wd.i();if(a in c.i){if(c.i[a]!=b)throw new Xd(a);}else{c.i[a]=b;if(b=c.j[a])for(var d=0,e=b.length;d<e;d++){var f=b[d],g=c.i;delete f.i[a];if(_.Jb(f.i)){for(var h=f.j.length,k=Array(h),m=0;m<h;m++)k[m]=g[f.j[m]];f.o.apply(f.v,k)}}delete c.j[a]}};_.Wd.i=function(){return _.Pd(_.Wd)};_.Zd=function(){_.aa.call(this)};_.z(_.Zd,_.aa);var Xd=function(){_.aa.call(this)};_.z(Xd,_.Zd);_.D("gbar.A",_.Md);_.Md.prototype.aa=_.Md.prototype.then;_.D("gbar.B",_.S);_.S.prototype.ba=_.S.prototype.jj;_.S.prototype.bb=_.S.prototype.tj;_.S.prototype.bd=_.S.prototype.qj;_.S.prototype.bf=_.S.prototype.aj;_.S.prototype.bg=_.S.prototype.ij;_.S.prototype.bh=_.S.prototype.fj;_.S.prototype.bj=_.S.prototype.Ui;_.S.prototype.bk=_.S.prototype.Ti;_.S.prototype.bl=_.S.prototype.kj;_.D("gbar.a",_.S.i());window.gbar&&window.gbar.ap&&window.gbar.ap(window.gbar.a);var $d=new Ed(window);_.Yd("api",$d);
var ae=_.Sd()||new _.Dd,be=window,ce=_.y(_.L(ae,8));be.__PVT=ce;_.Yd("eq",_.Vd);
}catch(e){_._DumpException(e)}
try{
_.de=function(a){this.J=_.x(a)};_.z(_.de,_.Q);
}catch(e){_._DumpException(e)}
try{
var ee=function(a){this.J=_.x(a)};_.z(ee,_.Q);var fe=function(){_.R.call(this);this.j=[];this.i=[]};_.z(fe,_.R);fe.prototype.o=function(a,b){this.j.push({features:a,options:b!=null?b:null})};fe.prototype.init=function(a,b,c){window.gapi={};var d=window.___jsl={};d.h=_.y(_.L(a,1));_.Ra(_.ud(a,12))!=null&&(d.dpo=_.Hb(_.J(a,12)));d.ms=_.y(_.L(a,2));d.m=_.y(_.L(a,3));d.l=[];_.K(b,1)&&(a=_.L(b,3))&&this.i.push(a);_.K(c,1)&&(c=_.L(c,2))&&this.i.push(c);_.D("gapi.load",(0,_.C)(this.o,this));return this};var ge=_.H(_.Rd,_.Hd,14);if(ge){var he=_.H(_.Rd,_.de,9)||new _.de,ie=new ee,je=new fe;je.init(ge,he,ie);_.Yd("gs",je)};
}catch(e){_._DumpException(e)}
})(this.gbar_);
// Google Inc.


